stages:
 - benchmark
 - publish

tpcc-benchmark:
  image: registry.gitlab.com/iproha94/tpcc-tarantool/benchmarking
  stage: benchmark
  artifacts:
    paths:
      - ./benchmarking/result.txt
      - ./benchmarking/version.txt
  script:
    - ./benchmarking/run-from-docker.sh
  only:
    - triggers
    - schedules

tpcc-publish:
  image: registry.gitlab.com/iproha94/tpcc-tarantool/publication
  stage: publish
  script:
    - cat ./benchmarking/result.txt
    - cat ./benchmarking/version.txt
    - ./publication/main.py ./benchmarking/result.txt ./benchmarking/version.txt
  only:
    - triggers
    - schedules
