stages:
 - benchmark
 - publish

tpcc-benchmark:
  image: registry.gitlab.com/iproha94/tpcc-tarantool
  stage: benchmark
  artifacts:
    paths:
      - result.txt
      - version.txt
  script:
    - ./run-from-docker.sh
  only:
    - triggers

tpcc-publish:
  image: registry.gitlab.com/iproha94/tpcc-tarantool
  stage: publish
  script:
   - cat result.txt
   - cat version.txt
   - python export.py auth.conf result.txt version.txt
  only:
   - triggers
